version: "3.8"

services:

  monitoring:

    container_name: monitoring
    image: monitoring-jvm:1.0
    build:
      context: ./
      dockerfile: ./src/main/docker/Dockerfile.jvm
      args:
        DB_HEROKU_SP: "true"
    
    ports:
      - 8080:8080
    networks:
      - heroku-net


networks:
  heroku-net:
    driver: bridge